### ISSUE TITLE
disable tab change

### ISSUE THREAD

**Issue by games4681** [JoseGamerPT/RealSkywars#15]
please add option to real skywars to disable tab change on game. I use the plugin of: https://www.spigotmc.org/resources/tab-1-5-1-21-1.57806/
And I don't want the plugins to conflict with each other.

**Comment by joserodpt** [comment]
This has been fixed in the upcoming 1.0.1 version. You can test it here, and thanks for the suggestion! [RealSkywars.jar.zip](https://github.com/user-attachments/files/17005597/RealSkywars.jar.zip)
