### ISSUE TITLE
Sepertate the language file

### ISSUE THREAD

**Issue by SnowCutieOwO** [JoseGamerPT/RealSkywars#16]
Just like the title said,
`language.yml` -> `/RealSkywars/languages/messages-xx_xx.yml` would be better and easier to maintain.
Reduced file size also helped a better develop environment I think :3

And I also noticed that your [RealRegions](https://modrinth.com/plugin/realregions) plugin have a wrong github link which lead us here

**Comment by joserodpt** [comment]
This will be added to the 1.1 version update of RealSkywars. Thanks for the suggestion!
