### ISSUE TITLE
Add some new modes in Config and add a Join game NPC

### ISSUE THREAD

**Issue by Happies123** [JoseGamerPT/RealSkywars#18]
Hello developers, I would like to suggest that you can improve the BungeCord mode by adding an NPC (such as Hypixel) to allow players to connect to the game through BungeCord. You can also add Lobby and Game options to identify whether the server is a Lobby server or a Game server. This way, you can do better

**Comment by joserodpt** [comment]
The NPC isn't connected to the RealSkywars single map server. The server "lobby" should connect to the server that contains RealSkywars in single map mode.

**Comment by Happies123** [comment]
I want to use RealSkywars' Level and achievements in the Lobby but I need use BungeeCord mode in realskywars Config

**Comment by joserodpt** [comment]
What you want to use is a shared RSW database between the lobby and the game server

**Comment by Happies123** [comment]
but ur RealSkywars can't custom ItemJoin

**Comment by joserodpt** [comment]
what?

**Comment by Happies123** [comment]
I change the Config "ITEM in lobby" but there is nothing to appear I want to remove the "Maps" Item on Lobby

**Comment by joserodpt** [comment]
Put it in slot -1 so it disappears

**Comment by Happies123** [comment]
ok thx
I translate the language file to Chinese Maybe I can give u next Sunday
This plugin is very good!

**Comment by joserodpt** [comment]
Ok. Make sure to open a issue with the new config file, thanks.
