### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by RangeBanenge** [JoseGamerPT/RealSkywars#7]
![image](https://github.com/joserodpt/RealSkywars/assets/123173065/d1a5e156-aa8b-4477-b2b9-a07e0dcdb430)
Where is this library? why is she not there?

**Comment by joserodpt** [comment]
That's RealPermissions. You can get the .jar on spigot and shade it into your project

**Comment by RangeBanenge** [comment]
I already understood, thank you

**Comment by RangeBanenge** [comment]
Sorry, but I encountered a problem adding a library, sometimes it is added but somehow crookedly and does not work after a while when I added the library to my small code I had no problems, but when working with a huge code there is a slight misunderstanding, can you show me exactly how I should do this?

**Comment by joserodpt** [comment]
IntelliJ -> Project Structure -> Project Settings -> Modules -> Add Library -> Select the .jar -> Select from Compile to Provided

**Comment by RangeBanenge** [comment]
![image](https://github.com/joserodpt/RealSkywars/assets/123173065/723e576e-f1ba-4a4f-b36c-6e17bd83df6f)
Yes I added, but when I compel the file in jar returns this package joserodpt.realpermissions.api does not exist

**Comment by RangeBanenge** [comment]
and yes I put Provided

**Comment by joserodpt** [comment]
Try to shade it also in the API, it worked for me

**Comment by RangeBanenge** [comment]
Please do it yourself in your code in the future, because I can't do it correctly, even the neural network doesn't help, and I've also seen a few bugs in pom.xml but it's so empty, it's easy to solve.
