### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RangeBanenge** [JoseGamerPT/RealSkywars#9]
![image](https://github.com/joserodpt/RealSkywars/assets/123173065/c5545dd5-0a32-423c-afc7-bce480f73bf0)
Please make changes to this line and also add the option to disable the game launch timer for chat (chat only)
And I would also like the cage not to be completely closed, make some kind of void at least in the middle, otherwise the player in some cells does not see anything.

**Comment by joserodpt** [comment]
> option to disable the game launch timer for chat (chat only)

This has been added in the config.yml in the latest commit

> And I would also like the cage not to be completely closed, make some kind of void at least in the middle, otherwise the player in some cells does not see anything.

The player can choose his own cage, and you can modify the default material for it.
